export const REQUEST_INFO_REQUEST = "REQUEST_INFO_REQUEST";
export const REQUEST_INFO_REQUEST_SUCCESS = "REQUEST_INFO_REQUEST_SUCCESS";
export const REQUEST_INFO_REQUEST_FAILURE = "REQUEST_INFO_REQUEST_FAILURE";
export const RESET_FORM_REQUEST = "RESET_FORM_REQUEST";
