export const REQUEST_CONTACT_REQUEST = "REQUEST_CONTACT_REQUEST";
export const REQUEST_CONTACT_REQUEST_SUCCESS =
  "REQUEST_CONTACT_REQUEST_SUCCESS";
export const REQUEST_CONTACT_REQUEST_FAILURE =
  "REQUEST_CONTACT_REQUEST_FAILURE";
