export const RETAILER_REQUEST = "RETAILER_REQUEST";
export const STOP_RETAILER_REQUEST = "STOP_RETAILER_REQUEST";

export const RETAILER_EXPORT_REQUEST = "RETAILER_EXPORT_REQUEST";
export const STOP_RETAILER_EXPORT_REQUEST = "STOP_RETAILER_EXPORT_REQUEST";
export const EXPORT_SUCCESS = "EXPORT_SUCCESS";
export const CLOSE_EXPORT = "CLOSE_EXPORT";

export const RETAILER_FAILED = "RETAILER_FAILED";

export const GET_ORDERS = "GET_ORDERS";
export const SET_ORDERS = "SET_ORDERS";
export const SORT_ORDERS = "SORT_ORDERS";
export const RESET_SORT_ORDERS = "RESET_SORT_ORDERS";

export const GET_INVENTORY = "GET_INVENTORY";
export const SET_INVENTORY = "SET_INVENTORY";
export const SORT_INVENTORY = "SORT_INVENTORY";
export const RESET_SORT_INVENTORY = "RESET_SORT_INVENTORY";

export const GET_CUSTOMER = "GET_CUSTOMER";
export const SET_CUSTOMER = "SET_CUSTOMER";
export const SORT_CUSTOMER = "SORT_CUSTOMER";
export const RESET_SORT_CUSTOMER = "RESET_SORT_CUSTOMER";

export const GET_OVERALL = "GET_OVERALL";
export const SET_OVERALL = "SET_OVERALL";
export const SORT_OVRERALL = "SORT_OVERALL";

export const GET_SALES_BY_ORDER = "GET_SALES_BY_ORDER";
export const SET_SALES_BY_ORDER = "SET_SALES_BY_ORDER";
export const SORT_SALES_BY_ORDER = "SORT_SALES_BY_ORDER";

export const GET_PAYMENT_BY_METHOD = "GET_PAYMENT_BY_METHOD";
export const SET_PAYMENT_BY_METHOD = "SET_PAYMENT_BY_METHOD";
export const SORT_PAYMENT_BY_METHOD = "SORT_PAYMENT_BY_METHOD";

export const GET_SALES_BY_PRODUCT = "GET_SALES_BY_PRODUCT";
export const SET_SALES_BY_PRODUCT = "SET_SALES_BY_PRODUCT";
export const SORT_SALES_BY_PRODUCT = "SORT_SALES_BY_PRODUCT";

export const GET_TOP_PRODUCT = "GET_TOP_PRODUCT";
export const SET_TOP_PRODUCT = "SET_TOP_PRODUCT";
export const SORT_TOP_PRODUCT = "SORT_TOP_PRODUCT";

export const GET_SALES_BY_CATEGORY = "GET_SALES_BY_CATEGORY";
export const SET_SALES_BY_CATEGORY = "SET_SALES_BY_CATEGORY";
export const SORT_SALES_BY_CATEGORY = "SORT_SALES_BY_CATEGORY";

export const GET_TOP_CATEGORY = "GET_TOP_CATEGORY";
export const SET_TOP_CATEGORY = "SET_TOP_CATEGORY";
export const SORT_TOP_CATEGORY = "SORT_TOP_CATEGORY";

export const GET_SALES_BY_CUSTOMER = "GET_SALES_BY_CUSTOMER";
export const SET_SALES_BY_CUSTOMER = "SET_SALES_BY_CUSTOMER";
export const SORT_SALES_BY_CUSTOMER = "SORT_SALES_BY_CUSTOMER";

export const GET_STAFF_REPORT = "GET_STAFF_REPORT";
export const SET_STAFF_REPORT = "SET_STAFF_REPORT";
export const SORT_STAFF_REPORT = "SORT_STAFF_REPORT";
export const RESET_SORT_STAFF = "RESET_SORT_STAFF";

export const GET_MARKETING_EFFICIENCY = "GET_MARKETING_EFFICIENCY";
export const SET_MARKETING_EFFICIENCY = "SET_MARKETING_EFFICIENCY";
export const SORT_MARKETING_EFFICIENCY = "SORT_MARKETING_EFFICIENCY";

export const GET_ORDER_DETAIL = "GET_ORDER_DETAIL";
export const SET_ORDER_DETAIL = "SET_ORDER_DETAIL";

export const GET_INVENTORY_DETAIL = "GET_INVENTORY_DETAIL";
export const SET_INVENTORY_DETAIL = "SET_INVENTORY_DETAIL";

export const GET_CUSTOMER_DETAIL = "GET_CUSTOMER_DETAIL";
export const SET_CUSTOMER_DETAIL = "SET_CUSTOMER_DETAIL";

export const GET_APPOINTMENT_CUSTOMER_DETAIL =
  "GET_APPOINTMENT_CUSTOMER_DETAIL";
export const SET_APPOINTMENT_CUSTOMER_DETAIL =
  "SET_APPOINTMENT_CUSTOMER_DETAIL";

export const RETAILER_DETAIL_REQUEST = "RETAILER_DETAIL_REQUEST";
export const STOP_RETAILER_DETAIL_REQUEST = "STOP_RETAILER_DETAIL_REQUEST";

export const SET_VISIBLE_ORDER_DETAIL = "SET_VISIBLE_ORDER_DETAIL";
export const SET_VISIBLE_INVENTORY_DETAIL = "SET_VISIBLE_INVENTORY_DETAIL";
export const SET_VISIBLE_CUSTOMER_DETAIL = "SET_VISIBLE_CUSTOMER_DETAIL";

export const SORT_CUSTOMER_APPOINTMENT = "SORT_CUSTOMER_APPOINTMENT";
export const RESET_SORT_CUSTOMER_APPOINTMENT =
  "RESET_SORT_CUSTOMER_APPOINTMENT";

export const UPLOAD_FILE_REQUEST = "UPLOAD_FILE_REQUEST";
export const STOP_UPLOAD_FILE_REQUEST = "STOP_UPLOAD_FILE_REQUEST";
export const CHANGE_IMAGE_PRODUCT_SUCCESS = "CHANGE_IMAGE_PRODUCT_SUCCESS";
