export const RETAILER_REQUEST = "RETAILER_REQUEST";
export const STOP_RETAILER_REQUEST = "STOP_RETAILER_REQUEST";

export const RETAILER_EXPORT_REQUEST = "RETAILER_EXPORT_REQUEST";
export const STOP_RETAILER_EXPORT_REQUEST = "STOP_RETAILER_EXPORT_REQUEST";
export const EXPORT_SUCCESS = "EXPORT_SUCCESS";
export const CLOSE_EXPORT = "CLOSE_EXPORT";

export const RETAILER_FAILED = "RETAILER_FAILED";

export const GET_ORDERS = "GET_ORDERS";
export const SET_ORDERS = "SET_ORDERS";

export const GET_INVENTORY = "GET_INVENTORY";
export const SET_INVENTORY = "SET_INVENTORY";

export const GET_CUSTOMER = "GET_CUSTOMER";
export const SET_CUSTOMER = "SET_CUSTOMER";

export const GET_OVERALL = "GET_OVERALL";
export const SET_OVERALL = "SET_OVERALL";
export const SORT_OVRERALL = "SORT_OVERALL";
