export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_REQUEST_SUCCESS = "LOGIN_REQUEST_SUCCESS";
export const LOGIN_REQUEST_FAILURE = "LOGIN_REQUEST_FAILURE";

export const USER_LOGOUT = "USER_LOGOUT";

export const GET_MY_ACCOUNT_REQUEST = "GET_MY_ACCOUNT_REQUEST";
export const GET_MY_ACCOUNT_SUCCESS = "GET_MY_ACCOUNT_SUCCESS";
export const GET_MY_ACCOUNT_FAILURE = "GET_MY_ACCOUNT_FAILURE";

export const UPDATE_MY_ACCOUNT_REQUEST = "UPDATE_MY_ACCOUNT_REQUEST";
export const UPDATE_MY_ACCOUNT_SUCCESS = "UPDATE_MY_ACCOUNT_SUCCESS";
export const UPDATE_MY_ACCOUNT_FAILURE = "UPDATE_MY_ACCOUNT_FAILURE";

export const NEWSLETTER_SUB_REQUEST = "NEWSLETTER_SUB_REQUEST";
export const NEWSLETTER_SUB_SUCCESS = "NEWSLETTER_SUB_SUCCESS";
export const NEWSLETTER_SUB_FAILURE = "NEWSLETTER_SUB_FAILURE";

export const GET_ALL_MERCHANT_REQUEST = "GET_ALL_MERCHANT_REQUEST";
export const GET_ALL_MERCHANT_SUCCESS = "GET_ALL_MERCHANT_SUCCESS";
export const GET_ALL_MERCHANT_FAILURE = "GET_ALL_MERCHANT_FAILURE";

export const GET_MERCHANT_BY_ID_REQUEST = "GET_MERCHANT_BY_ID_REQUEST";
export const GET_MERCHANT_BY_ID_SUCCESS = "GET_MERCHANT_BY_ID_SUCCESS";
export const GET_MERCHANT_BY_ID_FAILURE = "GET_MERCHANT_BY_ID_FAILURE";

export const GET_SUBSCRIPTION_REQUEST = "GET_SUBSCRIPTION_REQUEST";
export const GET_SUBSCRIPTION_SUCCESS = "GET_SUBSCRIPTION_SUCCESS";
export const GET_SUBSCRIPTION_FAILURE = "GET_SUBSCRIPTION_FAILURE";

export const GET_SUBSCRIPTION_BY_ID_REQUEST = "GET_SUBSCRIPTION_BY_ID_REQUEST";
export const GET_SUBSCRIPTION_BY_ID_SUCCESS = "GET_SUBSCRIPTION_BY_ID_SUCCESS";
export const GET_SUBSCRIPTION_BY_ID_FAILURE = "GET_SUBSCRIPTION_BY_ID_FAILURE";

export const GET_PACKAGE_REQUEST = "GET_PACKAGE_REQUEST";
export const GET_PACKAGE_SUCCESS = "GET_PACKAGE_SUCCESS";
export const GET_PACKAGE_FAILURE = "GET_PACKAGE_FAILURE";

export const CANCEL_SUBSCRIPTION_REQUEST = "CANCEL_SUBSCRIPTION_REQUEST";
export const CANCEL_SUBSCRIPTION_SUCCESS = "CANCEL_SUBSCRIPTION_SUCCESS";
export const CANCEL_SUBSCRIPTION_FAILURE = "CANCEL_SUBSCRIPTION_FAILURE";
