export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_REQUEST_SUCCESS = "LOGIN_REQUEST_SUCCESS";
export const LOGIN_REQUEST_FAILURE = "LOGIN_REQUEST_FAILURE";

export const GET_MY_ACCOUNT_REQUEST = "GET_MY_ACCOUNT_REQUEST";
export const GET_MY_ACCOUNT_SUCCESS = "GET_MY_ACCOUNT_SUCCESS";
export const GET_MY_ACCOUNT_FAILURE = "GET_MY_ACCOUNT_FAILURE";

export const UPDATE_MY_ACCOUNT_REQUEST = "UPDATE_MY_ACCOUNT_REQUEST";
export const UPDATE_MY_ACCOUNT_SUCCESS = "UPDATE_MY_ACCOUNT_SUCCESS";
export const UPDATE_MY_ACCOUNT_FAILURE = "UPDATE_MY_ACCOUNT_FAILURE";
